Change SharedKey  from `private` to `pub`
laysakura/serde-encrypt pull request #105
Opened 2022-04-12 16:17 UTC by kurikomoe

Related compile error:
```text
error[E0423]: cannot initialize a tuple struct which contains private fields
  --> src/main.rs:94:34
   |
94 |     const SHAREDKEY: SharedKey = SharedKey([0u8; 32]);
```

by default, tuple like struct is private and cannot be automatically built from static array `[u8; 32]`

Also, add test casees and alter the readme to suit the changes.

2022-04-12 23:29 UTC, laysakura commented on README.md
> -    let shared_key = [0u8; 32];  // or your peer reads from filesystem?
Sorry, README was totally wrong.

2022-04-12 23:57 UTC, laysakura commented
@kurikomoe You can ignore the current CI errors.

I created issues: #106 #107

2022-04-13 06:36 UTC, kurikomoe commented on README.md
> +    // let _: Vec<u8> = EncryptedMessage::serialize(encrypted_message);
I agree, but I just want to make it consistent with the other code snippets in the readme.
```rust
let encrypted_message = EncryptedMessage::deserialize(serialized_encrypted_message)?;
```

2022-04-13 06:41 UTC, kurikomoe commented on README.md
> +    const shared_key: SharedKey = SharedKey([0u8; 32]); // or your peer reads from elsewhere.
Good idea, but sometimes SharedKey may be shared by internet and be created at runtime ( if you use this as a library and use the third party solution to exchange keys).  `const fn` can only be used in compiling time. I think we should provide a method to create a non static SharedKey.

2022-04-13 06:58 UTC, kurikomoe commented
commits updated.

2022-04-13 08:54 UTC, laysakura requested changes

2022-04-13 08:54 UTC, laysakura commented on README.md
> +    // let _: Vec<u8> = EncryptedMessage::serialize(encrypted_message);
> I just want to make it consistent with the other code snippets in the readme.

I understand what you say but cannot fully agree with it.

People who like symmetry (and have enough knowledge about Rust syntax) would use `EncryptedMessage::serialize(encrypted_message);`, although README uses `encrypted_message.serialize();`.

2022-04-13 08:54 UTC, laysakura commented on README.md
> +    const shared_key: SharedKey = SharedKey([0u8; 32]); // or your peer reads from elsewhere.
Understood. How about having 2 constructors?:

- `fn new`
- `const fn new_const`

---
This is not far from your idea:

- `const fn new`
- `fn from`

but just a matter of API names.

2022-04-13 08:54 UTC, laysakura commented on serde-encrypt/src/shared_key.rs
> +}
[nits] add newline

2022-04-13 10:07 UTC, kurikomoe commented on README.md
> +    // let _: Vec<u8> = EncryptedMessage::serialize(encrypted_message);
Ok, just a matter of personal tastes, removed

2022-04-13 21:18 UTC, laysakura requested changes
almost done. thx

2022-04-13 21:18 UTC, laysakura commented on README.md
> +    const shared_key: SharedKey = SharedKey([0u8; 32]); // or your peer reads from elsewhere.
need to fix

2022-04-13 21:18 UTC, laysakura commented on README.md
> +
[nits] remove additional newline

2022-04-14 03:32 UTC, laysakura commented
LGTM

@kurikomoe Thank you so much for your work!
I'll release newer version soon.

2022-04-14 03:33 UTC, merged

2022-04-14 03:43 UTC, laysakura commented
@kurikomoe Released v0.7.0.

- https://github.com/laysakura/serde-encrypt/releases/tag/v0.7.0
- https://github.com/laysakura/serde-encrypt/blob/main/CHANGELOG.md#v070---2022-04-14